#!/bin/sh

set -e

currentver=`dpkg-query --showformat='${Version}' --show libpango-* | sed -r 's/[0-9]://'`
required50=1.50
required44=1.44

# https://unix.stackexchange.com/a/285928
if [ "$(printf '%s\n' "$required50" "$currentver" | sort -V | head -n1)" = "$required50" ]; then
	# Pango >= 1.50
	# same as Pango < 1.44
	sed -i 's/<border name="title_border" left="2" right="2" top="4" bottom="4"/<border name="title_border" left="2" right="2" top="4" bottom="3"/g' /usr/share/themes/human-theme/metacity-1/metacity-theme-1.xml
	sed -i 's/padding: 4px 3px 2px; \/\* WARNING/padding: 4px 3px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	sed -i 's/padding: 3px 3px 2px; \/\* WARNING/padding: 3px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	sed -i 's/margin: -7px -10px -5px; \/\* WARNING/margin: -7px -10px -4px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	echo "Update theme for Pango >= 1.50"
elif [ "$(printf '%s\n' "$required44" "$currentver" | sort -V | head -n1)" = "$required44" ]; then
	# Pango 1.44..1.49
	sed -i 's/<border name="title_border" left="2" right="2" top="4" bottom="3"/<border name="title_border" left="2" right="2" top="4" bottom="4"/g' /usr/share/themes/human-theme/metacity-1/metacity-theme-1.xml
	sed -i 's/padding: 4px 3px; \/\* WARNING/padding: 4px 3px 2px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	sed -i 's/padding: 3px; \/\* WARNING/padding: 3px 3px 2px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	sed -i 's/margin: -7px -10px -4px; \/\* WARNING/margin: -7px -10px -5px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	echo "Update theme for Pango >= 1.44"
else
	# Pango < 1.44
	# original behavior, same as Pango >= 1.50
	sed -i 's/<border name="title_border" left="2" right="2" top="4" bottom="4"/<border name="title_border" left="2" right="2" top="4" bottom="3"/g' /usr/share/themes/human-theme/metacity-1/metacity-theme-1.xml
	sed -i 's/padding: 4px 3px 2px; \/\* WARNING/padding: 4px 3px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	sed -i 's/padding: 3px 3px 2px; \/\* WARNING/padding: 3px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	sed -i 's/margin: -7px -10px -5px; \/\* WARNING/margin: -7px -10px -4px; \/\* WARNING/g' /usr/share/themes/human-theme/gtk-3.0/base.css
	echo "Update theme for Pango < 1.44"
fi

#DEBHELPER#
exit 0